version: "3.9"

services:
  youtube-dl:
    image: qmcgaw/youtube-dl-alpine
    container_name: youtube-dl
    volumes:
      - ./downloads:/downloads   # Dossier local pour stocker les vidéos
    environment:
      - AUTOUPDATE=yes           # Met à jour youtube-dl automatiquement
    entrypoint: youtube-dl       # Définit youtube-dl comme commande par défaut
    restart: unless-stopped

